import { ReactQueryProvider } from "@/components/providers";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Domine, Geist_Mono, Inter } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";

const domineSerif = Domine({
  variable: "--font-serif",
  subsets: ["latin"],
});

const inter = Inter({ variable: "--font-sans", subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Trackademic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${inter.variable} ${geistMono.variable} ${domineSerif.variable} overflow-x-hidden font-sans antialiased selection:bg-blue-400/30`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>{children}</ReactQueryProvider>
        </ThemeProvider>
        <Toaster theme="system" richColors />
      </body>
    </html>
  );
}
